### ISSUE TITLE
I can't install zhejiang2020 from github

### ISSUE THREAD

**Issue by Lxmic** [stemangiola/zhejiang2020#11]
> devtools::install_github("stemangiola/zhejiang2020", build_vignettes = TRUE)
Downloading GitHub repo stemangiola/zhejiang2020@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/stemangiola/zhejiang2020/tarball/HEAD' failed

**Comment by XueyiDong** [comment]
Hi @Lxmic ,

The problem is that your internet connection is not good so the download of the package is failed. Alternatively, you can do the following:

First, download the GitHub repository onto your computer from https://github.com/stemangiola/zhejiang2020/archive/master.zip . Unzip the file, and change the folder name into zhejiang2020.

Then, open terminal (终端) on your Mac or CMD on your PC, go to the folder where your `zhejiang2020` folder is (by using `cd` command), and run the following command:

`R CMD build zhejiang2020`

This builds the package and you will see a file named zhejiang2020_0.3.3.tar.gz (version number may differ for future updates). This is the package installable in R. Then, you can install it in R use the usual way (set your working directory to the folder where the file is):

`install.packages("zhejiang2020_0.3.3.tar.gz", repos = NULL)`

Hopefully this could be helpful.

Best wishes,
Xueyi

**Comment by stemangiola** [comment]
We are also trying to provide a light weight zhejiang2020_0.3.3.tar.gz file directly from github.

News soon!

**Comment by Lxmic** [comment]
> We are also trying to provide a light weight zhejiang2020_0.3.3.tar.gz file directly from github.
> 
> News soon!

**Comment by Lxmic** [comment]
> Hi @Lxmic ,
> 
> The problem is that your internet connection is not good so the download of the package is failed. Alternatively, you can do the following:
> 
> First, download the GitHub repository onto your computer from https://github.com/stemangiola/zhejiang2020/archive/master.zip . Unzip the file, and change the folder name into zhejiang2020.
> 
> Then, open terminal (终端) on your Mac or CMD on your PC, go to the folder where your `zhejiang2020` folder is (by using `cd` command), and run the following command:
> 
> `R CMD build zhejiang2020`
> 
> This builds the package and you will see a file named zhejiang2020_0.3.3.tar.gz (version number may differ for future updates). This is the package installable in R. Then, you can install it in R use the usual way (set your working directory to the folder where the file is):
> 
> `install.packages("zhejiang2020_0.3.3.tar.gz", repos = NULL)`
> 
> Hopefully this could be helpful.
> 
> Best wishes,
> Xueyi

Thanks，I solved it

**Comment by stemangiola** [comment]
Hello @Lxmic,  that's great. How did you solve it?

**Comment by Lxmic** [comment]
Hello@stemangiola, I actually reinstall R and devtools, then try again the code. It works.
